version: '3.8'

services:
  nproxy:
    build:
      dockerfile: ./build/Dockerfile
    ports:
      - "8000:8000"
    container_name: nproxy
    restart: always
    networks:
      - nproxy_vpn

  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - "8080:80"
    networks:
      - nproxy_vpn

networks:
  nproxy_vpn:
    driver: bridge